<?php

/**
 * Preprocess function for leaflet_locatecontrol.
 */
function leaflet_locatecontrol_preprocess_leaflet_map(array &$variables) {
  $config = \Drupal::config('leaflet_plugins.settings');

  // add the cache tag, so that the output gets invalidated when the config is saved
  \Drupal::service('renderer')->addCacheableDependency($variables, $config);
  
  $variables['#attached']['library'][] = 'leaflet_locatecontrol/leaflet-locatecontrol';
  $variables['#attached']['library'][] = 'leaflet_locatecontrol/leaflet-locatecontrol-drupal';

  $variables['#attached']['drupalSettings']['leaflet_plugins']['locatecontrol']['control'] = $config->get('locatecontrol_control') ?? false;
  $variables['#attached']['drupalSettings']['leaflet_plugins']['locatecontrol']['position'] = $config->get('locatecontrol_position') ?? 'bottomright';
}

